<?xml version="1.0" ?>
<robot name="rviz_test_name" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:arg name="id" default="100"/>
    <name>aruco_$(arg id)</name>
    <xacro:arg name="sizemm" default="100"/>

    <xacro:include filename="$(find aruco_model_generation)/urdf/common/base_aruco_panel.urdf.xacro"/>

    <xacro:macro name="sized_panel" params="sizemm">
        <xacro:aruco_panel width="${sizemm/1000.0}" thickness="0.001" id="$(arg id)"/>
    </xacro:macro>

    <xacro:sized_panel sizemm="$(arg sizemm)"/>
</robot>
